### ISSUE TITLE
Publish `@wavs/solidity` via CI

### ISSUE THREAD

**Issue by dakom** [BreadchainCoop/layer-middleware#33]
Depends on https://github.com/Lay3rLabs/wavs-middleware/issues/32

**Comment by RonTuretzky** [comment]
Need to add our devops person dijar to the org to address this issue

**Comment by ethanfrey** [comment]
@dakom @Reecepbcups can you please discuss this issue today?

Let me know if we can close this or if we do need this, please specify clearly what is needed

**Comment by reecepbcups** [comment]
Yes, We should add this. Seeing a ~18x speedup for fresh install of the middleware package (54 seconds -> 3 seconds). This is **not** a blocker for 0.4. @dakom can manually publish for 0.4.0 and we add CI after for future bumps.

## What is needed
- [ ] Add package info into this repos contracts/solidity - https://github.com/Lay3rLabs/WAVS/pull/372/files. May be able to just put it where I have https://github.com/Lay3rLabs/wavs-middleware/blob/dev/package.json now
- [ ] [Generate an NPM token](https://docs.npmjs.com/creating-and-viewing-access-tokens)
- [ ] Add this to the repo secrets in github as `NPM_TOKEN`
- [ ] [github action](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-nodejs-packages), likely follow tags instead of release
- [ ] Publish release and verify it is auto published to https://www.npmjs.com/package/@wavs/solidity

ref from `github action` link

```yaml
name: Publish Package to npmjs
on:
  # TODO: on push of tags: 'v*' instead?
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
```

## Benchmark

With `github:Lay3rLabs/wavs-middleware#v0.4.0-alpha.5` git reference
```
real    0m54.272s
user    0m9.043s
sys     0m1.642s
```

Without this git reference
```
real    0m2.896s
user    0m2.126s
sys     0m0.415s
```
